apiVersion: apps/v1
kind: Deployment
metadata:
  name: incognito
  labels:
    app: incognito
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: incognito
  template:
    metadata:
      labels:
        app: incognito
    spec:
      containers:
        - name: incognito
          image: "incognitochain/incognito-mainnet:20200910_1"
          ports:
            - name: rpc
              containerPort: 9334
              protocol: TCP
            - name: node
              containerPort: 9433
              protocol: TCP
          resources:
            requests:
              cpu: 2
              memory: 1Gi
          env:
            - name: MININGKEY
              value: <Validator Key>
            - name: GETH_NAME
              value: mainnet.infura.io/v3/<Infura Project ID>
            - name: GETH_PROTOCOL
              value: https
            - name: GETH_PORT
              value: ""
            - name: BOOTNODE_IP
              value: "mainnet-bootnode.incognito.org:9330"
            - name: TESTNET
              value: "false"
            - name: LIMIT_FEE
              value: "1"
            - name: RPC_PORT
              value: "9334"
            - name: NODE_PORT
              value: "9433"
          volumeMounts:
            - name: data
              mountPath: /data
        - name: tunnel
          image: adrianchifor/alpine-ssh:latest
          imagePullPolicy: Always
          command:
            - /scripts/tunnel.sh
          livenessProbe:
            exec:
              command:
                - /usr/bin/pgrep
                - ssh
            initialDelaySeconds: 10
            periodSeconds: 60
          volumeMounts:
            - name: script
              mountPath: /scripts
            - name: ssh
              mountPath: /ssh-tunnel
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: incognito-data
        - name: script
          configMap:
            name: incognito-ssh-script
            defaultMode: 0700
        - name: ssh
          secret:
            secretName: incognito-ssh
            defaultMode: 0400
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: incognito-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: incognito-ssh-script
data:
  tunnel.sh: |
    #!/bin/sh
    ssh -fNT -R 0.0.0.0:9334:127.0.0.1:9334 -o ExitOnForwardFailure=yes -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -i /ssh-tunnel/key incognito@<Public VM>
    ssh -fNT -R 0.0.0.0:9433:127.0.0.1:9433 -o ExitOnForwardFailure=yes -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -i /ssh-tunnel/key incognito@<Public VM>
    sleep infinity
---
apiVersion: v1
kind: Secret
metadata:
  name: incognito-ssh
type: Opaque
data:
  key: <base64 SSH private key>
