apiVersion: v1
kind: ConfigMap
metadata:
  name: incognito-ssh-script
data:
  health.sh: |
    #!/bin/sh
    if [ $(pgrep ssh | wc -l) -lt 2 ]; then
      exit 1
    else
      exit 0
    fi
  tunnel.sh:
