apiVersion: apps/v1
kind: Deployment
metadata:
  name: incognito
  labels:
    app: incognito
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: incognito
  template:
    metadata:
      labels:
        app: incognito
    spec:
      containers:
        - name: incognito
          image:
          ports:
            - name: rpc
              containerPort: 9334
              protocol: TCP
            - name: node
              containerPort: 9433
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 400Mi
          env:
            - name: MININGKEY
              value:
            - name: GETH_NAME
              value:
            - name: GETH_PROTOCOL
              value: https
            - name: GETH_PORT
              value: ""
            - name: BOOTNODE_IP
              value: "mainnet-bootnode.incognito.org:9330"
            - name: TESTNET
              value: "false"
            - name: LIMIT_FEE
              value: "1"
            - name: RPC_PORT
              value: "9334"
            - name: NODE_PORT
              value: "9433"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: appdir
              mountPath: /root/.incognito
        - name: tunnel
          image:
          imagePullPolicy: Always
          command:
            - /scripts/tunnel.sh
          livenessProbe:
            exec:
              command:
                - /scripts/health.sh
            initialDelaySeconds: 10
            periodSeconds: 60
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - name: script
              mountPath: /scripts
            - name: ssh
              mountPath: /ssh-tunnel
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: incognito-data
        - name: script
          configMap:
            name: incognito-ssh-script
            defaultMode: 0700
        - name: ssh
          secret:
            secretName: incognito-ssh
            defaultMode: 0400
        - name: appdir
          emptyDir:
            medium: Memory
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      -
